"""add_speed

Revision ID: d7350d7bc52b
Revises: 6d50c5f59b06
Create Date: 2024-06-19 23:42:05.076647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7350d7bc52b'
down_revision: Union[str, None] = '6d50c5f59b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spaceships', sa.Column('speed', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spaceships', 'speed')
    # ### end Alembic commands ###
