"""init_migr

Revision ID: 6d50c5f59b06
Revises: 
Create Date: 2024-06-19 23:28:15.902471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d50c5f59b06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_name', 'last_name', 'rank', name='uq_officer')
    )
    op.create_table('spaceships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alignment', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ship_class', sa.String(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('crew_size', sa.Integer(), nullable=False),
    sa.Column('armed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('spaceship_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spaceship_id'], ['spaceships.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('spaceship_id', 'officer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignments')
    op.drop_table('spaceships')
    op.drop_table('officers')
    # ### end Alembic commands ###
